<?xml version="1.0" encoding="utf-8"?><Database Name="BBMS_DB" Class="MyLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BBMS_DB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="BBMSP.Properties.Settings" SettingsPropertyName="BBMS_DBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBLOOD" Member="TBLOODs">
    <Type Name="TBLOOD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BLOODTYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TBLOOD_TDONOR" Member="TDONORs" ThisKey="ID" OtherKey="ID_BLOOD" Type="TDONOR" />
      <Association Name="TBLOOD_TPATIENT" Member="TPATIENTs" ThisKey="ID" OtherKey="ID_BLOOD" Type="TPATIENT" />
    </Type>
  </Table>
  <Table Name="dbo.TDONOR" Member="TDONORs">
    <Type Name="TDONOR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CIN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ID_BLOOD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ALLERGIES" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="TDONOR_TDONATION" Member="TDONATIONs" ThisKey="ID" OtherKey="ID_DONOR" Type="TDONATION" />
      <Association Name="TBLOOD_TDONOR" Member="TBLOOD" ThisKey="ID_BLOOD" OtherKey="ID" Type="TBLOOD" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TPATIENT" Member="TPATIENTs">
    <Type Name="TPATIENT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CIN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ID_BLOOD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ALLERGIES" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="TPATIENT_TINJECTION" Member="TINJECTIONs" ThisKey="ID" OtherKey="ID_PATIENT" Type="TINJECTION" />
      <Association Name="TBLOOD_TPATIENT" Member="TBLOOD" ThisKey="ID_BLOOD" OtherKey="ID" Type="TBLOOD" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TDONATION" Member="TDONATIONs">
    <Type Name="TDONATION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DONOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CIN_DONOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OPERATION_DATE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY_DONATED" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TDONOR_TDONATION" Member="TDONOR" ThisKey="ID_DONOR" OtherKey="ID" Type="TDONOR" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINJECTION" Member="TINJECTIONs">
    <Type Name="TINJECTION">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PATIENT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CIN_PATIENT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OPERATION_DATE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY_INJECTED" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TPATIENT_TINJECTION" Member="TPATIENT" ThisKey="ID_PATIENT" OtherKey="ID" Type="TPATIENT" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.USERS" Member="USERs">
    <Type Name="USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CIN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="USER_INFOS_USER" Member="INFOS_USERs" ThisKey="ID" OtherKey="ID_USER" Type="INFOS_USER" />
    </Type>
  </Table>
  <Table Name="dbo.INFOS_USERS" Member="INFOS_USERs">
    <Type Name="INFOS_USER">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_USER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CIN_USER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LOGIN_TIME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LOGOUT_TIME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="USER_INFOS_USER" Member="USER" ThisKey="ID_USER" OtherKey="ID" Type="USER" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SERIAL_CODE" Member="SERIAL_CODEs">
    <Type Name="SERIAL_CODE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SERIAL_NUMBER" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CITY" Member="CITies">
    <Type Name="CITY">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CITY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ADMINS" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CIN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.FILTER_D_B" Method="FILTER_D_B">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="FILTER_D_BResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CIN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ID_BLOOD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ALLERGIES" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.FILTER_P_B" Method="FILTER_P_B">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="FILTER_P_BResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CIN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ID_BLOOD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ALLERGIES" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.FILTER_PHONE" Method="FILTER_PHONE">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="FILTER_PHONEResult">
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.FILTER_Q_ASC" Method="FILTER_Q_ASC">
    <ElementType Name="FILTER_Q_ASCResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BLOODTYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.FILTER_Q_DESC" Method="FILTER_Q_DESC">
    <ElementType Name="FILTER_Q_DESCResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BLOODTYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.FILTER_Q_ID" Method="FILTER_Q_ID">
    <ElementType Name="FILTER_Q_IDResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BLOODTYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>